from copy import deepcopy
from pathlib import Path

import viper_config as cfg


PACKAGE_DIR = cfg.DATA_DIR / "ha_packages"
PACKAGE_FILE = PACKAGE_DIR / "viper_vision_package.yaml"
INSTALL_NOTES_FILE = PACKAGE_DIR / "INSTALL_VIPER_PACKAGE.txt"


DEFAULT_PACKAGE_OPTIONS = {
    "viper_host": cfg.PC_IP,
    "viper_port": cfg.FLASK_PORT,
    "front_doorbell_mqtt_topic": "",
    "back_doorbell_mqtt_topic": "",
    "fridge_door_entity": "",
    "freezer_door_entity": "",
    "filter_sensor_entity": "",
    "ice_maker_switch_entity": "switch.refrigerator_cubed_ice",
    "ice_maker_keep_on_entity": "input_boolean.keep_ice_maker_on",
    "ice_usage_counter_entity": "counter.ice_usage_counter",
    "ice_auto_off_seconds": 5,
    "ice_empty_threshold": 15,
    "ice_refill_hours": 4,
    "vacuum_status_entity": "sensor.cinderella_status",
    "vacuum_error_entity": "sensor.cinderella_vacuum_error",
    "dock_error_entity": "sensor.cinderella_dock_dock_error",
    "dock_mop_drying_entity": "binary_sensor.cinderella_dock_mop_drying",
    "include_doorbell": True,
    "include_fridge": True,
    "include_filter": True,
    "include_ice_maker": True,
    "include_cinderella": True,
    "include_cinderella_debug": False,
}


def get_default_package_options():
    return deepcopy(DEFAULT_PACKAGE_OPTIONS)


def package_options_from_config(config_data=None):
    options = get_default_package_options()
    data = cfg.validate_and_normalize_config(config_data) if config_data is not None else cfg.load_config()
    doorbell = cfg.get_resolved_doorbell_settings(data, include_env=True)
    options["viper_host"] = data.get("viper_host") or cfg.PC_IP
    options["viper_port"] = data.get("flask_port") or cfg.FLASK_PORT
    options["front_doorbell_mqtt_topic"] = doorbell.get("front_doorbell_mqtt_topic", "")
    options["back_doorbell_mqtt_topic"] = doorbell.get("back_doorbell_mqtt_topic", "")
    return options


def package_options_from_discovery(discovery_result, base_options=None):
    """Build conservative package options from discovery results.

    The wizard should let users confirm these guesses before writing a package.
    """
    options = deepcopy(base_options or get_default_package_options())
    if not discovery_result or not discovery_result.get("ok"):
        return options

    categories = discovery_result.get("categories", {})
    options["fridge_door_entity"] = _first_entity_id(categories.get("fridge_sensors", []), "door")
    options["freezer_door_entity"] = _first_entity_id(categories.get("freezer_sensors", []), "door")
    options["filter_sensor_entity"] = _first_entity_id(categories.get("filter_sensors", []))
    options["vacuum_status_entity"] = _first_entity_id(categories.get("roborock_entities", [])) or _first_entity_id(categories.get("vacuum_entities", []))
    ice_candidate = _first_entity_id(categories.get("ice_maker_candidates", []), "switch.") or _first_entity_id(categories.get("ice_maker_candidates", []))
    if ice_candidate:
        options["ice_maker_switch_entity"] = ice_candidate
    return options


def generate_viper_ha_package(options=None):
    """Return a Home Assistant package YAML string for manual installation."""
    opts = _normalize_options(options)
    base_url = f"http://{opts['viper_host']}:{opts['viper_port']}"
    lines = [
        "# Viper Vision Home Assistant package",
        "# Generated by Viper Vision. Review entity IDs before installing.",
        "# Install as /config/packages/viper_vision_package.yaml, then reload YAML or restart Home Assistant.",
        "",
        "rest_command:",
        _rest_command_block("ring_vision_front", f"{base_url}/doorbell-webhook"),
        _rest_command_block("ring_vision_back", f"{base_url}/doorbell-webhook/back"),
        _broadcast_command_block("viper_broadcast", f"{base_url}/remote/broadcast"),
        _broadcast_command_block("viper_broadcast_push", f"{base_url}/remote/broadcast_push"),
        _broadcast_command_block("cinderella_broadcast", f"{base_url}/remote/broadcast"),
        _broadcast_command_block("ha_announce", f"{base_url}/remote/broadcast"),
        _cinderella_command_block(f"{base_url}/cinderella"),
    ]

    helper_lines = _helper_blocks(opts)
    if helper_lines:
        lines.extend(["", *helper_lines])

    automations = []
    if opts["include_doorbell"]:
        automations.extend(_doorbell_automations(opts))
    if opts["include_ice_maker"]:
        automations.extend(_ice_maker_automations(opts))
    if opts["include_fridge"]:
        automations.extend(_fridge_automations(opts))
    if opts["include_filter"]:
        automations.extend(_filter_automations(opts))
    if opts["include_cinderella"]:
        automations.extend(_cinderella_automations(opts))
    if opts["include_cinderella_debug"]:
        automations.extend(_cinderella_debug_automation(opts))

    if automations:
        lines.extend(["", "automation:", *automations])

    return "\n".join(line.rstrip() for line in lines if line is not None).rstrip() + "\n"


def write_viper_ha_package(options=None, output_path=None):
    path = Path(output_path) if output_path else PACKAGE_FILE
    path.parent.mkdir(parents=True, exist_ok=True)
    package_text = generate_viper_ha_package(options)
    path.write_text(package_text, encoding="utf-8")
    return path


def get_install_instructions(package_filename="viper_vision_package.yaml"):
    return "\n".join([
        "Viper Vision Home Assistant Package Install",
        "",
        "1. In Home Assistant, make sure packages are enabled.",
        "   Add this to /config/configuration.yaml if it is not already present:",
        "",
        "   homeassistant:",
        "     packages: !include_dir_named packages",
        "",
        "2. Create this folder if needed:",
        "",
        "   /config/packages",
        "",
        f"3. Copy {package_filename} into:",
        "",
        f"   /config/packages/{package_filename}",
        "",
        "4. In Home Assistant, run Settings > System > Restart Home Assistant.",
        "   A YAML reload may work for some sections, but restart is safest after adding packages.",
        "",
        "5. After restart, verify these service names exist in Developer Tools > Actions:",
        "",
        "   rest_command.viper_broadcast",
        "   rest_command.viper_broadcast_push",
        "   rest_command.ring_vision_front",
        "   rest_command.ring_vision_back",
        "   rest_command.cinderella_event",
        "",
        "6. If automations do not appear, check Settings > System > Logs for YAML errors.",
        "",
    ])


def write_install_instructions(output_path=None, package_filename="viper_vision_package.yaml"):
    path = Path(output_path) if output_path else INSTALL_NOTES_FILE
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(get_install_instructions(package_filename), encoding="utf-8")
    return path


def write_package_bundle(options=None, package_path=None, notes_path=None):
    package_file = write_viper_ha_package(options, package_path)
    notes_file = write_install_instructions(notes_path, package_file.name)
    return {"package": package_file, "instructions": notes_file}


def _normalize_options(options=None):
    opts = get_default_package_options()
    if isinstance(options, dict):
        opts.update(options)
    opts["viper_host"] = str(opts.get("viper_host") or cfg.PC_IP).strip()
    opts["viper_port"] = int(opts.get("viper_port") or cfg.FLASK_PORT)
    for key in [
        "front_doorbell_mqtt_topic",
        "back_doorbell_mqtt_topic",
        "fridge_door_entity",
        "freezer_door_entity",
        "filter_sensor_entity",
        "ice_maker_switch_entity",
        "ice_maker_keep_on_entity",
        "ice_usage_counter_entity",
        "vacuum_status_entity",
        "vacuum_error_entity",
        "dock_error_entity",
        "dock_mop_drying_entity",
    ]:
        opts[key] = str(opts.get(key) or "").strip()
    opts["ice_auto_off_seconds"] = max(1, int(opts.get("ice_auto_off_seconds") or 5))
    opts["ice_empty_threshold"] = max(1, int(opts.get("ice_empty_threshold") or 15))
    opts["ice_refill_hours"] = max(1, int(opts.get("ice_refill_hours") or 4))
    for key in [
        "include_doorbell",
        "include_fridge",
        "include_filter",
        "include_ice_maker",
        "include_cinderella",
        "include_cinderella_debug",
    ]:
        opts[key] = bool(opts.get(key))
    return opts


def _rest_command_block(name, url, timeout=10):
    return "\n".join([
        f"  {name}:",
        f"    url: {_q(url)}",
        "    method: POST",
        f"    timeout: {timeout}",
    ])


def _broadcast_command_block(name, url):
    return "\n".join([
        f"  {name}:",
        f"    url: {_q(url)}",
        "    method: POST",
        '    content_type: "application/json"',
        "    payload: >",
        "      {\"broadcast_text\": {{ message | tojson }},",
        "       \"channel\": {{ channel | default('') | tojson }}}",
        "    timeout: 15",
    ])


def _cinderella_command_block(url):
    return "\n".join([
        "  cinderella_event:",
        f"    url: {_q(url)}",
        "    method: POST",
        '    content_type: "application/json"',
        "    payload: >",
        "      {\"event\": {{ event | tojson }},",
        "       \"error\": {{ error | default('') | tojson }},",
        "       \"source\": {{ source | default('vacuum') | tojson }}}",
        "    timeout: 15",
    ])


def _helper_blocks(opts):
    blocks = []
    keep_on = opts["ice_maker_keep_on_entity"]
    counter = opts["ice_usage_counter_entity"]
    if keep_on.startswith("input_boolean."):
        blocks.extend([
            "input_boolean:",
            f"  {keep_on.split('.', 1)[1]}:",
            '    name: "Keep Ice Maker On"',
            "",
        ])
    if counter.startswith("counter."):
        blocks.extend([
            "counter:",
            f"  {counter.split('.', 1)[1]}:",
            '    name: "Ice Usage Counter"',
            "    initial: 0",
            "    step: 1",
        ])
    return blocks


def _doorbell_automations(opts):
    triggers = []
    choices = []
    if opts["front_doorbell_mqtt_topic"]:
        triggers.extend([
            "    - trigger: mqtt",
            f"      topic: {_q(opts['front_doorbell_mqtt_topic'])}",
            "      payload: 'ON'",
            "      id: front",
        ])
        choices.extend(_choice_action("front", ["            - action: rest_command.ring_vision_front"]))
    if opts["back_doorbell_mqtt_topic"]:
        triggers.extend([
            "    - trigger: mqtt",
            f"      topic: {_q(opts['back_doorbell_mqtt_topic'])}",
            "      payload: 'ON'",
            "      id: back",
        ])
        choices.extend(_choice_action("back", ["            - action: rest_command.ring_vision_back"]))
    if not triggers:
        return []
    return [
        "- id: viper_vision_door_ai_monitor",
        "  alias: 'Viper Vision: Door AI Monitor'",
        "  description: Sends selected doorbell motion events to Viper Vision.",
        "  mode: single",
        "  triggers:",
        *triggers,
        "  actions:",
        "    - choose:",
        *choices,
    ]


def _ice_maker_automations(opts):
    switch = opts["ice_maker_switch_entity"]
    keep_on = opts["ice_maker_keep_on_entity"]
    counter = opts["ice_usage_counter_entity"]
    if not switch or not keep_on or not counter:
        return []
    return [
        "- id: viper_ice_maker_auto_off",
        "  alias: 'Viper Vision: Ice Maker Auto-Off and Usage'",
        "  mode: restart",
        "  triggers:",
        "    - trigger: state",
        f"      entity_id: {switch}",
        "      to: 'on'",
        "      for:",
        f"        seconds: {opts['ice_auto_off_seconds']}",
        "  conditions:",
        "    - condition: state",
        f"      entity_id: {keep_on}",
        "      state: 'off'",
        "  variables:",
        f"    next_ice_count: \"{{{{ states('{counter}') | int(0) + 1 }}}}\"",
        "  actions:",
        "    - action: switch.turn_off",
        "      target:",
        f"        entity_id: {switch}",
        "    - action: counter.increment",
        "      target:",
        f"        entity_id: {counter}",
        "    - delay: '00:00:02'",
        "    - action: rest_command.viper_broadcast",
        "      data:",
        "        message: \"Ice dispensed. Counter is now at {{ next_ice_count }}.\"",
        "",
        "- id: viper_ice_maker_turn_on_when_empty",
        "  alias: 'Viper Vision: Ice Maker Turn On When Empty'",
        "  mode: single",
        "  triggers:",
        "    - trigger: numeric_state",
        f"      entity_id: {counter}",
        f"      above: {opts['ice_empty_threshold']}",
        "  conditions:",
        "    - condition: state",
        f"      entity_id: {keep_on}",
        "      state: 'off'",
        "  actions:",
        "    - action: input_boolean.turn_on",
        "      target:",
        f"        entity_id: {keep_on}",
        "    - action: switch.turn_on",
        "      target:",
        f"        entity_id: {switch}",
        "    - action: rest_command.viper_broadcast",
        "      data:",
        "        message: \"The ice bin is low. Viper started a fresh batch.\"",
        "",
        "- id: viper_ice_maker_fill_and_reset",
        "  alias: 'Viper Vision: Ice Maker Fill and Reset'",
        "  mode: restart",
        "  triggers:",
        "    - trigger: state",
        f"      entity_id: {keep_on}",
        "      to: 'on'",
        "  actions:",
        "    - delay:",
        f"        hours: {opts['ice_refill_hours']}",
        "    - action: switch.turn_off",
        "      target:",
        f"        entity_id: {switch}",
        "    - action: input_boolean.turn_off",
        "      target:",
        f"        entity_id: {keep_on}",
        "    - action: counter.reset",
        "      target:",
        f"        entity_id: {counter}",
        "    - action: rest_command.viper_broadcast",
        "      data:",
        "        message: \"Ice refill cycle is complete. The counter has been reset.\"",
    ]


def _fridge_automations(opts):
    fridge = opts["fridge_door_entity"]
    freezer = opts["freezer_door_entity"]
    triggers = []
    choices = []
    if fridge:
        triggers.extend(_state_trigger(fridge, "on", "fridge_open"))
        triggers.extend(_state_trigger(fridge, "off", "fridge_closed"))
        choices.extend(_broadcast_choice("fridge_open", "The fridge door is open.", "fridge_open"))
        choices.extend(_broadcast_choice("fridge_closed", "The fridge door is closed.", "fridge_closed"))
    if freezer:
        triggers.extend(_state_trigger(freezer, "on", "freezer_open"))
        triggers.extend(_state_trigger(freezer, "off", "freezer_closed"))
        choices.extend(_broadcast_choice("freezer_open", "The freezer door is open.", "freezer_open"))
        choices.extend(_broadcast_choice("freezer_closed", "The freezer door is closed.", "freezer_closed"))
    if not triggers:
        return []
    return [
        "- id: viper_refrigerator_door_announcements",
        "  alias: 'Viper Vision: Refrigerator Door Announcements'",
        "  mode: single",
        "  triggers:",
        *triggers,
        "  actions:",
        "    - choose:",
        *choices,
    ]


def _filter_automations(opts):
    sensor = opts["filter_sensor_entity"]
    if not sensor:
        return []
    return [
        "- id: viper_refrigerator_filter_notifications",
        "  alias: 'Viper Vision: Refrigerator Filter Notifications'",
        "  mode: single",
        "  triggers:",
        "    - trigger: numeric_state",
        f"      entity_id: {sensor}",
        "      above: 74",
        "      below: 90",
        "      id: filter_75",
        "    - trigger: numeric_state",
        f"      entity_id: {sensor}",
        "      above: 89",
        "      below: 100",
        "      id: filter_90",
        "    - trigger: numeric_state",
        f"      entity_id: {sensor}",
        "      above: 99",
        "      id: filter_100",
        "  actions:",
        "    - choose:",
        *_choice_action("filter_75", ["            - action: rest_command.viper_broadcast_push", "              data:", "                message: \"The refrigerator filter is 75 percent used.\""]),
        *_choice_action("filter_90", ["            - action: rest_command.viper_broadcast_push", "              data:", "                message: \"The refrigerator filter is 90 percent used.\""]),
        *_choice_action("filter_100", ["            - action: rest_command.viper_broadcast_push", "              data:", "                message: \"The refrigerator filter is at 100 percent and should be replaced now.\""]),
    ]


def _cinderella_automations(opts):
    status = opts["vacuum_status_entity"]
    vacuum_error = opts["vacuum_error_entity"]
    dock_error = opts["dock_error_entity"]
    drying = opts["dock_mop_drying_entity"]
    triggers = []
    choices = []
    if vacuum_error:
        triggers.extend([
            "    - trigger: state",
            f"      entity_id: {vacuum_error}",
            "      not_to: ['none', 'unknown', 'unavailable']",
            "      id: vacuum_error",
        ])
        choices.extend(_choice_action("vacuum_error", ["            - action: rest_command.cinderella_event", "              data:", "                event: 'error'", f"                error: \"{{{{ states('{vacuum_error}') }}}}\"", "                source: 'vacuum'"]))
    if dock_error:
        triggers.extend([
            "    - trigger: state",
            f"      entity_id: {dock_error}",
            "      not_to: ['ok', 'unknown', 'unavailable']",
            "      id: dock_error",
        ])
        choices.extend(_choice_action("dock_error", ["            - action: rest_command.cinderella_event", "              data:", "                event: 'error'", f"                error: \"{{{{ states('{dock_error}') }}}}\"", "                source: 'dock'"]))
    if status:
        triggers.extend(_multi_to_trigger(status, "['starting', 'cleaning', 'spot_cleaning', 'zoned_cleaning', 'zone_cleaning', 'segment_cleaning', 'mapping', 'patrol', 'robot_status_mopping', 'clean_mop_cleaning', 'clean_mop_mopping', 'segment_mopping', 'segment_clean_mop_cleaning', 'segment_clean_mop_mopping', 'zoned_mopping', 'zoned_clean_mop_cleaning', 'zoned_clean_mop_mopping']", 1, "departure"))
        triggers.extend(_multi_to_trigger(status, "['washing_mop', 'washing_the_mop', 'washing_the_mop_2', 'back_to_dock_washing_duster']", 2, "washing"))
        triggers.extend(_multi_to_trigger(status, "['emptying', 'emptying_bin', 'emptying_dustbin', 'emptying_the_bin']", 2, "emptying"))
        triggers.extend(_multi_to_trigger(status, "['returning', 'returning_home', 'docking', 'going_to_target', 'going_to_wash_the_mop', 'attaching_the_mop', 'detaching_the_mop', 'air_drying_stopping']", 2, "returning"))
        triggers.extend(_multi_to_trigger(status, "['charging', 'docked', 'charging_complete', 'idle']", 2, "victory"))
        triggers.extend(_multi_to_trigger(status, "['paused', 'remote_control_active', 'manual_mode', 'in_call', 'locked']", 2, "paused"))
        triggers.extend(_multi_to_trigger(status, "['unknown', 'charger_disconnected', 'charging_problem', 'error', 'shutting_down', 'updating', 'device_offline', 'egg_attack']", 2, "status_update"))
        for event in ["departure", "washing", "emptying", "returning", "victory", "paused", "status_update"]:
            choices.extend(_choice_action(event, ["            - action: rest_command.cinderella_event", "              data:", f"                event: '{event}'"]))
    if drying:
        triggers.extend(_state_trigger(drying, "on", "drying", seconds=2))
        choices.extend(_choice_action("drying", ["            - action: rest_command.cinderella_event", "              data:", "                event: 'drying'"]))
    if not triggers:
        return []
    return [
        "- id: viper_cinderella_event_router",
        "  alias: 'Viper Vision: Cinderella Event Router'",
        "  mode: queued",
        "  max: 10",
        "  triggers:",
        *triggers,
        "  actions:",
        "    - delay: '00:00:01'",
        "    - choose:",
        *choices,
    ]


def _cinderella_debug_automation(opts):
    entities = [opts[key] for key in ["vacuum_status_entity", "vacuum_error_entity", "dock_error_entity", "dock_mop_drying_entity"] if opts.get(key)]
    if not entities:
        return []
    return [
        "- id: viper_cinderella_debug_log",
        "  alias: 'Viper Vision: Cinderella Debug Log'",
        "  mode: queued",
        "  triggers:",
        "    - trigger: state",
        "      entity_id:",
        *[f"        - {entity}" for entity in entities],
        "  actions:",
        "    - action: system_log.write",
        "      data:",
        "        level: warning",
        "        message: >",
        "          Cinderella change | entity={{ trigger.entity_id }} | from={{ trigger.from_state.state if trigger.from_state else 'none' }} | to={{ trigger.to_state.state if trigger.to_state else 'none' }}",
    ]


def _state_trigger(entity_id, to_state, trigger_id, seconds=None):
    lines = [
        "    - trigger: state",
        f"      entity_id: {entity_id}",
        f"      to: '{to_state}'",
    ]
    if seconds:
        lines.extend(["      for:", f"        seconds: {seconds}"])
    lines.append(f"      id: {trigger_id}")
    return lines


def _multi_to_trigger(entity_id, to_states, seconds, trigger_id):
    return [
        "    - trigger: state",
        f"      entity_id: {entity_id}",
        f"      to: {to_states}",
        "      for:",
        f"        seconds: {seconds}",
        f"      id: {trigger_id}",
    ]


def _broadcast_choice(trigger_id, message, channel):
    return _choice_action(trigger_id, [
        "            - action: rest_command.viper_broadcast",
        "              data:",
        f"                message: {_q(message)}",
        f"                channel: {channel}",
    ])


def _choice_action(trigger_id, action_lines):
    return [
        "        - conditions:",
        "            - condition: trigger",
        f"              id: {trigger_id}",
        "          sequence:",
        *action_lines,
    ]


def _first_entity_id(entities, contains=None):
    for entity in entities or []:
        entity_id = entity.get("entity_id", "")
        text = f"{entity_id} {entity.get('friendly_name', '')}".lower()
        if contains is None or contains.lower() in text:
            return entity_id
    return ""


def _q(value):
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'
