services:
  # --- MQTT BROKER ---
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # --- HOME ASSISTANT ---
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    volumes:
      - ./hass_config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    depends_on:
      - mosquitto

  # --- RING TO MQTT BRIDGE ---
  ring-mqtt:
    image: tsightler/ring-mqtt
    container_name: ring-mqtt
    restart: unless-stopped
    ports:
      - "8554:8554"   # RTSP Video
      - "55123:55123" # Web UI
    volumes:
      - ./ring_data:/data
    environment:
      - ENABLE_WEB_UI=true
      - RING_MQTT_WEB_PORT=55123
      - MQTTHOST=mosquitto # Uses the internal Docker name
    depends_on:
      - mosquitto